export class ServiceOut{
    from:string;
    to:string;
    averageCost:number;
    averageTime:number;
    averageDistance:number;
    averagePassangerCount:number;
    averageTip:number;
    averageTollAmount:number;
    morningTripsCount:number;
    afternoonTripsCount:number;
    eveningTripsCount:number;
    mondayTripsCount:number;
    tuesdayTripsCount:number;
    wednesdayTripsCount:number;
    thursdayTripsCount:number;
    fridayTripsCount:number;
    saturdayTripsCount:number;
    sundayTripsCount:number;
}